baseurl = "/"
languageCode = "en-us"
title = "Spoonhead"
theme = "hugo-spoonhead-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-112020005-1"
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Spoonhead Music - progressive psy, breaks and bass"
	description = "New Zealand's master of psychedelic chunk"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "New Zealand's master of psychedelic chunk, **Spoonhead**, is known for his uncommon hybrid of progressive-psy, breaks & bass. "   
		# The icons will be shown if you enter your username
		soundcloud = "spoonhead"
		facebook = "spoonhead.music"
		github = "RaySingerNZ"
		instagram = "spoonhead.music"
		dribbble = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Ray Spoonhead",
			"Design: [Ray Spoonhead](//github.com/RaySingerNZ)",
		]


	[params.about]
		hide  = false
		title = "Kia Ora friends, Spoonhead is back!"
		content = "After a few years getting my life together after the Christchurch earthquakes, I'm stoked to annouce that Spoonhead is back in business. I've recently returned from some amazing shows where I was blown away by the response to my music. I'm now super pumped to write more and get creative AF. Check out my latest release 'An Uncommon Hybrid' below."


	[params.portfolio]
		hide  = false
		title = "Quick News"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Day 2 Unlocked."
			description = "Amazing festival in Golden Bay in Jan 2017 - pictures to come"

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "An Uncommon Hybrid EP."
			description = "Out now on WEAPON Records."

	[params.recentposts]
		hide  = false
		title = "Recent stories / posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "If you'd like to book me for your event or chat about releasing music, use any of the channels below."

		# This can be exact coordinates or a searchable address in google maps
		phone = "+64 27 599 5677"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "spoonhead.music@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 0

[[menu.main]]
    name = "About / PressKit"
    url  = "about"
    weight = 5

[[menu.main]]
    name = "Stories / Blog"
    url  = "post/"
    weight = 10
