name = "Spoonhead"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/digitalcraftsman/hugo-strata-theme/blob/master/LICENSE.md"
description = ""
homepage = "//github.com/digitalcraftsman/hugo-strata-theme"
tags = ["image gallery", "contact form", "google analytics", "customizable", "blog", "single-page"]
features = ["", ""]
min_version = 0.16

[author]
  name = "spoonhead"
  homepage = "//github.com/RaySingerNZ"

# If porting an existing theme
[original]
  name = "AJ"
  homepage = "//html5up.net/"
  repo = ""
